/**
 * JongnoSolo Spot Database
 * Contains selected spots in Jongno that are highly suited for solo travelers.
 * Fields: id, name, category, subCategory, area, purpose[], style, budget, duration, description, soloReason, mapUrl, image, tags[]
 */
window.JONGNO_SPOTS = [
  // --- CAFE CATEGORY (6 spots) ---
  {
    id: "cafe_onion_anguk",
    name: "어니언 안국 (onion Anguk)",
    category: "cafe",
    subCategory: "대형 한옥 베이커리 카페",
    area: "북촌",
    purpose: ["힐링", "사진", "관광"],
    style: "활발함",
    budget: 12000,
    duration: 1.5,
    description: "전통 한옥의 고즈넉한 멋을 고스란히 살린 마당과 현대적인 감각이 어우러진 베이커리 카페입니다. 대청마루에 앉아 하늘을 보며 빵을 즐길 수 있습니다.",
    soloReason: "넓은 대청마루와 마당 좌석이 있어 혼자서도 부담 없이 한옥의 개방감을 느끼며 여유를 즐기기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=어니언 안국",
    image: "assets/hanok_cafe.png",
    tags: ["한옥개방감", "베이커리맛집", "핫플레이스"]
  },
  {
    id: "cafe_cha_뜰",
    name: "차 마시는 뜰",
    category: "cafe",
    subCategory: "전통 한옥 찻집",
    area: "삼청동",
    purpose: ["힐링", "산책", "사진"],
    style: "조용함",
    budget: 10000,
    duration: 1.5,
    description: "ㄷ자 모양의 아름다운 한옥 마당 정원을 품은 삼청동의 대표적인 전통 찻집입니다. 정갈한 차와 한과를 정성스레 대접합니다.",
    soloReason: "정원이 한눈에 보이는 조용한 창가 1인석이 있어, 혼자 조용히 정원을 바라보며 차 한 잔의 사색을 즐기기에 최고의 장소입니다.",
    mapUrl: "https://map.kakao.com/?q=삼청동 차마시는뜰",
    image: "assets/hanok_cafe.png",
    tags: ["전통차", "마당정원", "조용한사색"]
  },
  {
    id: "cafe_green_mile",
    name: "그린마일커피 북촌점",
    category: "cafe",
    subCategory: "한옥 루프탑 감성 카페",
    area: "북촌",
    purpose: ["사진", "힐링"],
    style: "조용함",
    budget: 8000,
    duration: 1.0,
    description: "모던한 인테리어의 카페로, 3층 루프탑에 올라가면 북촌 한옥마을의 아름다운 기와지붕 곡선이 눈앞에 펼쳐지는 숨은 조망 명소입니다.",
    soloReason: "시끌벅적하지 않고 차분한 분위기로, 루프탑에서 기와 풍경을 바라보며 나만의 멋진 사진을 남길 수 있습니다.",
    mapUrl: "https://map.kakao.com/?q=그린마일커피 북촌점",
    image: "assets/hanok_cafe.png",
    tags: ["기와뷰", "루프탑", "조용한분위기"]
  },
  {
    id: "cafe_sasa",
    name: "카페 사사 (SASA)",
    category: "cafe",
    subCategory: "서순라길 숲뷰 한옥 카페",
    area: "인사동",
    purpose: ["힐링", "산책", "사진"],
    style: "조용함",
    budget: 9000,
    duration: 1.2,
    description: "돌담길이 아름다운 서순라길에 위치한 카페로, 나무와 숲이 어우러진 돌담 뷰를 보며 한국식 디저트와 막걸리 에이드를 즐길 수 있습니다.",
    soloReason: "돌담길을 정면으로 마주하는 바 테이블 좌석이 마련되어 있어 혼자 창밖의 초록빛 자연과 돌담을 보며 휴식하기에 최적입니다.",
    mapUrl: "https://map.kakao.com/?q=카페 사사",
    image: "assets/hanok_cafe.png",
    tags: ["서순라길", "돌담뷰", "디저트맛집"]
  },
  {
    id: "cafe_daechung",
    name: "대충유원지 인왕산필운",
    category: "cafe",
    subCategory: "인왕산 숲속 뷰 루프탑 바/카페",
    area: "서촌",
    purpose: ["힐링", "사진"],
    style: "조용함",
    budget: 8500,
    duration: 1.2,
    description: "인왕산의 거대한 숲과 암벽이 파노라마처럼 내려다보이는 빌딩 꼭대기의 아늑한 카페 겸 바 공간입니다. 인더스트리얼과 나무가 조화를 이룹니다.",
    soloReason: "긴 바(Bar) 형태의 좌석이 주를 이루어 혼자 조용히 커피나 위스키 한 잔을 마시며 창밖 인왕산 자연 풍경을 감상하기 완벽합니다.",
    mapUrl: "https://map.kakao.com/?q=대충유원지 인왕산필운",
    image: "assets/hanok_cafe.png",
    tags: ["인왕산뷰", "바테이블", "숲속전망"]
  },
  {
    id: "cafe_tongin",
    name: "통인동 커피공방",
    category: "cafe",
    subCategory: "서촌 골목길 핸드드립 로스터리",
    area: "서촌",
    purpose: ["힐링", "문화"],
    style: "활발함",
    budget: 6500,
    duration: 1.0,
    description: "서촌 주민들의 사랑방 역할을 하는 따뜻한 우드 톤의 전문 로스터리 샵입니다. 갓 볶아낸 원두의 고소하고 신선한 향이 골목에 퍼집니다.",
    soloReason: "통창을 바라보는 바 테이블에서 골목길을 걷는 사람들과 서촌 한옥 풍경을 바라보며 신선한 핸드드립 커피를 즐기기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=통인동 커피공방",
    image: "assets/hanok_cafe.png",
    tags: ["핸드드립", "로컬골목", "커피향가득"]
  },

  // --- RESTAURANT CATEGORY (6 spots) ---
  {
    id: "rest_doma",
    name: "도마 인사점",
    category: "restaurant",
    subCategory: "마약된장찌개와 한옥 솥밥",
    area: "인사동",
    purpose: ["맛집", "관광"],
    style: "활발함",
    budget: 18000,
    duration: 1.0,
    description: "서울에서 가장 맛있는 된장찌개로 유명한 곳으로, 정갈한 개인용 나무 쟁반에 따뜻한 솥밥과 밑반찬이 한 상 가득 나오는 한식당입니다.",
    soloReason: "혼밥 손님을 위한 깔끔한 1인 한 상 차림 형태로 제공되어 부담 없이 든든한 정통 한식을 즐길 수 있습니다.",
    mapUrl: "https://map.kakao.com/?q=도마 인사점",
    image: "assets/hanok_restaurant.png",
    tags: ["솥밥정식", "마약된장찌개", "든든한한상"]
  },
  {
    id: "rest_hoho",
    name: "호호식당 익선동",
    category: "restaurant",
    subCategory: "한옥에서 즐기는 일본 가정식",
    area: "익선동",
    purpose: ["맛집", "사진", "힐링"],
    style: "조용함",
    budget: 20000,
    duration: 1.2,
    description: "아담하고 고풍스러운 한옥 중정을 중심으로 아늑한 방들이 배치된 퓨전 일식 가정식 맛집입니다. 돈카츠와 사케동이 대표 메뉴입니다.",
    soloReason: "조용하고 감성적인 인테리어로, 따사로운 햇살이 비치는 중정을 바라보며 정갈하게 혼자 식사하기 매우 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=호호식당 익선동",
    image: "assets/hanok_restaurant.png",
    tags: ["돈카츠", "한옥중정", "정갈한식사"]
  },
  {
    id: "rest_mildang",
    name: "밀과 보리",
    category: "restaurant",
    subCategory: "서촌 골목길 토속 보리밥",
    area: "서촌",
    purpose: ["맛집", "힐링", "관광"],
    style: "조용함",
    budget: 11000,
    duration: 1.0,
    description: "서촌 골목 한구석에서 정겨운 시골 어머니의 손맛을 전하는 한식 노포입니다. 제철 나물이 듬뿍 담긴 보리밥과 곤드레밥이 일품입니다.",
    soloReason: "정감 있고 소박한 분위기로, 주인 할머니의 친절함 덕분에 고향 집에 온 듯 편안하게 혼밥하기 좋은 숨겨진 맛집입니다.",
    mapUrl: "https://map.kakao.com/?q=서촌 밀과보리",
    image: "assets/hanok_restaurant.png",
    tags: ["보리밥정식", "서촌노포", "시골집반찬"]
  },
  {
    id: "rest_flower_rice",
    name: "꽃밥에피다",
    category: "restaurant",
    subCategory: "친환경 유기농 한식 코스/비빔밥",
    area: "인사동",
    purpose: ["맛집", "힐링"],
    style: "조용함",
    budget: 25000,
    duration: 1.2,
    description: "미쉐린 그린 스타를 획득한 친환경 유기농 한식 전문점으로, 한국 전통 보자기 무늬처럼 아름답게 꾸민 '보자기 비빔밥'이 대표적입니다.",
    soloReason: "화사하고 차분한 인테리어 속에서 정성스럽고 건강한 1인 비빔밥 세트를 음미하며 대접받는 느낌을 누릴 수 있습니다.",
    mapUrl: "https://map.kakao.com/?q=인사동 꽃밥에피다",
    image: "assets/hanok_restaurant.png",
    tags: ["미쉐린그린스타", "보자기비빔밥", "친환경유기농"]
  },
  {
    id: "rest_jogum",
    name: "조금 (Jogum)",
    category: "restaurant",
    subCategory: "인사동 전통 솥밥 명가",
    area: "인사동",
    purpose: ["맛집", "힐링"],
    style: "조용함",
    budget: 18000,
    duration: 1.0,
    description: "우드 톤의 차분하고 고요한 일본식 다다미방 감성이 살짝 더해진 전통 한옥 솥밥 전문점입니다. 은행, 새우, 굴이 듬뿍 들어간 솥밥을 냅니다.",
    soloReason: "가게 내부가 조용하게 가라앉아 있어 혼자서 갓 지은 뜨끈한 돌솥 밥을 긁어먹으며 나만의 식사 시간에 집중하기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=인사동 조금",
    image: "assets/hanok_restaurant.png",
    tags: ["전통솥밥", "인사동노포", "조용한다다미"]
  },
  {
    id: "rest_imun",
    name: "이문설농탕",
    category: "restaurant",
    subCategory: "한국 최초로 등록된 110년 노포 설렁탕",
    area: "인사동",
    purpose: ["맛집", "관광"],
    style: "활발함",
    budget: 13000,
    duration: 0.8,
    description: "서울 미래유산이자 100년이 넘는 역사를 지닌 원조 설렁탕 노포입니다. 기름기를 걷어내 맑고 슴슴한 국물이 특징입니다.",
    soloReason: "혼밥 테이블이 많고 회전율이 빨라, 뜨끈하고 깊은 고기 국물로 혼자 든든하게 한 끼 해결하고 싶은 여행자에게 최적입니다.",
    mapUrl: "https://map.kakao.com/?q=이문설농탕",
    image: "assets/hanok_restaurant.png",
    tags: ["설렁탕노포", "백년가게", "슴슴한맑은탕"]
  },

  // --- POPUP & CULTURE CATEGORY (6 spots) ---
  {
    id: "popup_sulwhasoo",
    name: "설화수 하우스 북촌",
    category: "popup",
    subCategory: "1930년대 양옥과 한옥의 융합 문화공간",
    area: "북촌",
    purpose: ["문화", "사진", "관광"],
    style: "조용함",
    budget: 0,
    duration: 1.5,
    description: "전통 한옥과 현대식 양옥이 정원으로 연결된 아모레퍼시픽의 플래그십 스토어이자 무료 전시 공간입니다. 세련된 공예품과 한국적 미감을 선보입니다.",
    soloReason: "고요하고 격조 높은 정원을 홀로 산책하고 도슨트처럼 한옥 구석구석 전시품을 감상하며 1인의 깊이 있는 문화 체험이 가능합니다.",
    mapUrl: "https://map.kakao.com/?q=설화수의 집 북촌",
    image: "assets/hanok_popup.png",
    tags: ["전통공예", "한옥과양옥", "감성정원"]
  },
  {
    id: "popup_ground_seesaw",
    name: "그라운드시소 서촌",
    category: "popup",
    subCategory: "자연 친화적 건축과 사진 전시관",
    area: "서촌",
    purpose: ["문화", "사진", "힐링"],
    style: "활발함",
    budget: 15000,
    duration: 2.0,
    description: "가운데에 연못과 둥근 중정이 있는 독특한 현대식 자연 친화 건축물로, 트렌디하고 화사한 다큐멘터리 사진전이나 일러스트 전시가 상시 열립니다.",
    soloReason: "혼자 오디오 가이드를 들으며 나만의 템포로 전시를 관람하고, 아름다운 중정 연못가에서 물멍을 때리며 인생 사진을 남기기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=그라운드시소 서촌",
    image: "assets/hanok_popup.png",
    tags: ["인생샷명소", "물멍연못", "트렌디전시"]
  },
  {
    id: "popup_cheongun",
    name: "청운문학도서관",
    category: "popup",
    subCategory: "인왕산 자락 숲속 한옥 도서관",
    area: "서촌",
    purpose: ["힐링", "산책", "문화"],
    style: "조용함",
    budget: 0,
    duration: 2.0,
    description: "인왕산 자락의 맑은 공기 속에 지어진 한옥 공공도서관입니다. 폭포 소리가 들리는 정자와 대청마루에서 책을 읽을 수 있는 도심 속 지상낙원입니다.",
    soloReason: "자연의 소리 외에는 아무 소리도 나지 않는 숲속 한옥에서 혼자 조용히 독서와 사색에 빠져 심신을 치유하기 완벽한 공간입니다.",
    mapUrl: "https://map.kakao.com/?q=청운문학도서관",
    image: "assets/hanok_popup.png",
    tags: ["숲속도서관", "한옥독서", "정자폭포"]
  },
  {
    id: "popup_mmca",
    name: "국립현대미술관 서울관 (MMCA)",
    category: "popup",
    subCategory: "도심 속 열린 미술관",
    area: "삼청동",
    purpose: ["문화", "관광", "산책"],
    style: "활발함",
    budget: 5000,
    duration: 2.0,
    description: "종친부 한옥 건물과 조화를 이루는 넓은 잔디마당이 매력적인 현대 미술관입니다. 한국 작가들의 최첨단 미디어 아트부터 조각까지 넓은 공간에서 소개합니다.",
    soloReason: "전시관이 넓어 다른 관람객의 방해 없이 나만의 감상에 젖어들 수 있으며, 전시 후 잔디 마당 의자에 앉아 해넘이를 즐기기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=국립현대미술관 서울관",
    image: "assets/hanok_popup.png",
    tags: ["현대미술", "넓은마당", "문화지성"]
  },
  {
    id: "popup_boan",
    name: "통의동 보안여관",
    category: "popup",
    subCategory: "예술 여관과 지하 인디 서점",
    area: "서촌",
    purpose: ["문화", "힐링"],
    style: "조용함",
    budget: 0,
    duration: 1.5,
    description: "1930년대 시인들이 머물던 오래된 여관 목조건물을 보존하여 현대 미술 전시장과 지하 1층 독립 서점(보안책방)으로 탈바꿈한 대안 예술 공간입니다.",
    soloReason: "오래된 나무 바닥의 삐걱거리는 소리를 들으며 고요한 여관 골목길 예술품을 홀로 감상하고 독립 서적들을 읽기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=통의동 보안여관",
    image: "assets/hanok_popup.png",
    tags: ["예술여관", "문화공간", "보안책방"]
  },
  {
    id: "popup_jeongdok",
    name: "정독도서관 정원",
    category: "popup",
    subCategory: "역사적인 정원과 한옥 독서 숲",
    area: "북촌",
    purpose: ["산책", "힐링", "관광"],
    style: "조용함",
    budget: 0,
    duration: 1.5,
    description: "옛 경기고등학교 건물을 도서관으로 개조한 곳으로, 계절마다 벚꽃과 단풍이 터지는 흐드러진 숲 정원과 야외 한옥형 정자가 마련되어 있습니다.",
    soloReason: "드넓은 도서관 마당 의자나 한옥 정자에 앉아 바람에 흔들리는 나뭇잎 소리를 들으며 혼자 멍하니 산책하고 쉬기 최고의 야외 정원입니다.",
    mapUrl: "https://map.kakao.com/?q=정독도서관",
    image: "assets/hanok_popup.png",
    tags: ["벚꽃명소", "도심정원", "한옥정자"]
  },

  // --- SHOP CATEGORY (6 spots) ---
  {
    id: "shop_granhand",
    name: "그랑핸드 북촌 (Granhand)",
    category: "shop",
    subCategory: "한옥 속 향기로운 향수 공방",
    area: "북촌",
    purpose: ["힐링", "사진", "문화"],
    style: "조용함",
    budget: 25000,
    duration: 1.0,
    description: "오래된 한옥을 개조하여 자연의 풀 냄새, 나무 향, 흙내음을 시그니처 향수로 제조해 판매하는 감성 멀티샵입니다. 마포백에 이름을 도장으로 찍어줍니다.",
    soloReason: "공간 가득 편안한 우디 향이 가득하여 혼자서 여유롭게 시향지를 시향하며 나만의 취향에 맞는 향을 고르기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=그랑핸드 북촌",
    image: "assets/hanok_shop.png",
    tags: ["우디향가득", "한옥시향", "시그니처각인"]
  },
  {
    id: "shop_ofr_seoul",
    name: "오에프알 서울 (Ofr. Seoul)",
    category: "shop",
    subCategory: "파리 감성 서촌 골목 소품 편집샵",
    area: "서촌",
    purpose: ["사진", "문화"],
    style: "활발함",
    budget: 20000,
    duration: 1.0,
    description: "서촌의 빈티지한 골목길 주택을 개조한 소품샵으로, 프랑스 파리에서 날아온 유니크한 에코백, 독립 서적, 빈티지 의류 및 주얼리를 가득 모아 놓았습니다.",
    soloReason: "구불구불한 다락방 같은 주택 내부를 탐험하듯 돌아다니며 혼자 눈치 보지 않고 아기자기한 빈티지 소품들을 구경하고 득템하기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=오에프알 서울",
    image: "assets/hanok_shop.png",
    tags: ["에코백성지", "빈티지책방", "골목편집샵"]
  },
  {
    id: "shop_ssamziegil",
    name: "인사동 쌈지길",
    category: "shop",
    subCategory: "한국 전통 공예품 & 액세서리 정원",
    area: "인사동",
    purpose: ["관광", "사진"],
    style: "활발함",
    budget: 15000,
    duration: 1.5,
    description: "나선형 계단식 골목길 구조를 본따 만든 전통 수공예 쇼핑 몰입니다. 젊은 신진 작가들의 귀여운 한복 액세서리, 도자기, 일러스트 굿즈들이 모여 있습니다.",
    soloReason: "계단을 오르는 독특한 건축 동선을 따라 걸으며 혼자서 편안히 한글 간판 상점들과 오기자기한 소공방들을 기웃거리기 재미있습니다.",
    mapUrl: "https://map.kakao.com/?q=인사동 쌈지길",
    image: "assets/hanok_shop.png",
    tags: ["수공예품", "달팽이길", "한복액세서리"]
  },
  {
    id: "shop_ikseon_vintage",
    name: "익선동 빈티지 보니",
    category: "shop",
    subCategory: "익선동 한옥 속 빈티지 소품샵",
    area: "익선동",
    purpose: ["사진", "관광"],
    style: "조용함",
    budget: 10000,
    duration: 0.8,
    description: "골목길 한옥 천장의 서까래 아래 가득 채워진 레트로 키치 감성의 컵, 그릇, 수입 인형, 빈티지 의류들을 판매하는 샵입니다.",
    soloReason: "오밀조밀한 한옥 공간 안에 귀여운 아이템이 꽉 차 있어 홀로 동심으로 돌아가 빈티지 소품들을 천천히 만져보며 구경하기 좋습니다.",
    mapUrl: "https://map.kakao.com/?q=빈티지보니",
    image: "assets/hanok_shop.png",
    tags: ["레트로감성", "서까래천장", "아기자기그릇"]
  },
  {
    id: "shop_onemorebag",
    name: "원모어백 (One More Bag)",
    category: "shop",
    subCategory: "서촌 패브릭 백 & 일러스트 소품샵",
    area: "서촌",
    purpose: ["사진", "문화"],
    style: "조용함",
    budget: 15000,
    duration: 0.8,
    description: "다양한 국내 일러스트 작가들의 천 가방, 필통, 파우치, 키링과 문구 용품을 모아 둔 서촌의 유명 편집숍입니다. 아기자기함이 가득합니다.",
    soloReason: "주변을 신경 쓰지 않는 차분한 음악 속에서 나만의 귀여운 다이어리 꾸미기 스티커나 편안한 에코백을 구경하며 취향을 탐닉하기 적합합니다.",
    mapUrl: "https://map.kakao.com/?q=원모어백",
    image: "assets/hanok_shop.png",
    tags: ["에코백추천", "다꾸스티커", "일러스트키링"]
  },
  {
    id: "shop_haeinsa",
    name: "해인글방",
    category: "shop",
    subCategory: "인사동 수제 한지 및 캘리그라피 소품",
    area: "인사동",
    purpose: ["문화", "관광", "힐링"],
    style: "조용함",
    budget: 8000,
    duration: 1.0,
    description: "전통 수제 한지 편지지와 예쁜 한글 캘리그라피 책갈피, 목도장 등을 제작하는 인사동 한구석의 서정적인 수공예 소품샵입니다.",
    soloReason: "한지의 포근한 질감을 손끝으로 느껴보고, 은은한 먹향 속에서 소중한 사람에게 보낼 1인 한지 엽서 한 장을 고르는 고풍스러운 힐링이 가능합니다.",
    mapUrl: "https://map.kakao.com/?q=인사동 해인글방",
    image: "assets/hanok_shop.png",
    tags: ["수제한지", "캘리그라피", "먹향가득"]
  }
];
